name: Save DataFrame to CSV

on: [push]

jobs:
  save-to-csv:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Pandas
        run: pip install pandas

      - name: Run main.py
        run: python main.py
